/**
 * Football API Integration (Local JSON Version)
 * Fetches match data from local 'data/matches.json' file
 * Generated by Python scraper script
 */

class FootballAPI {
    constructor() {
        this.dataURL = 'data/matches.json';
    }

    /**
     * جلب المباريات من الملف المحلي
     * @returns {Promise} - قائمة المباريات
     */
    async getTodayMatches() {
        try {
            // إضافة timestamp لمنع التخزين المؤقت (Caching)
            const url = `${this.dataURL}?t=${new Date().getTime()}`;
            const response = await fetch(url);

            if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            }

            const matches = await response.json();
            return this.transformData(matches);
        } catch (error) {
            console.error('خطأ في جلب المباريات المحلية:', error);
            // العودة لبيانات فارغة أو تجريبية
            return [];
        }
    }

    /**
     * تحويل صيغة البيانات من Scraper للصيغة التي يفهمها الواجهة
     * @param {Array} matches - البيانات الخام من JSON
     */
    transformData(matches) {
        return matches.map(match => {
            // تحليل النتيجة "2 - 1"
            let homeScore = null;
            let awayScore = null;
            if (match.score && match.score.includes('-')) {
                const parts = match.score.split('-');
                homeScore = parts[0].trim();
                awayScore = parts[1].trim();
            }

            // تحديد الحالة (Standardizing status)
            let status = 'SCHEDULED';
            if (match.status.includes('مباشر')) status = 'IN_PLAY';
            if (match.status.includes('انتهت')) status = 'FINISHED';
            if (match.status.includes('استراحة')) status = 'PAUSED';

            // تحويل الصيغة لتطابق الواجهة الحالية
            return {
                id: match.id,
                status: status, // IN_PLAY, SCHEDULED, FINISHED
                utcDate: this.convertTimeToDate(match.time), // محاولة تحويل الوقت

                competition: {
                    name: match.league || match.championship // دعم المفتاحين للاحتياط
                },

                homeTeam: {
                    name: match.homeTeam.name,
                    crest: match.homeTeam.logo
                },

                awayTeam: {
                    name: match.awayTeam.name,
                    crest: match.awayTeam.logo
                },

                score: {
                    fullTime: {
                        home: homeScore,
                        away: awayScore
                    }
                },

                channel: match.channel || 'غير محدد'
            };
        });
    }

    /**
     * تحويل الوقت (HH:MM) إلى Date Object تقريبي لليوم
     */
    convertTimeToDate(timeStr) {
        if (!timeStr) return new Date().toISOString();

        const now = new Date();
        const [hours, minutes] = timeStr.split(':');

        const matchDate = new Date(now);
        matchDate.setHours(parseInt(hours) || 0);
        matchDate.setMinutes(parseInt(minutes) || 0);

        return matchDate.toISOString();
    }

    /**
     * تنسيق الوقت للعرض
     */
    formatMatchTime(utcDate) {
        const date = new Date(utcDate);
        const hours = date.getHours().toString().padStart(2, '0');
        const minutes = date.getMinutes().toString().padStart(2, '0');
        return `${hours}:${minutes}`;
    }

    /**
     * ترجمة الحالة
     */
    getMatchStatus(status) {
        if (status === 'IN_PLAY') return '🔴 مباشر';
        if (status === 'FINISHED') return 'انتهت';
        if (status === 'PAUSED') return 'استراحة';
        return 'لم تبدأ';
    }
}

// تصدير instance واحد
const footballAPI = new FootballAPI();
